[workspace]
resolver = "2"
members = [
    "crates/meowscript",
    "crates/meowscript-cli",
    "crates/meowscript-wasm",
]

[workspace.package]
version = "1.0.0"
edition = "2024"
repository = "https://github.com/AlenVelocity/MeowScript"
rust-version = "1.88"

[workspace.dependencies]
meowscript = { path = "crates/meowscript", version = "1.0.0" }
indexmap = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
